# Overwritting configs
train_batch_size: 256
eval_batch_size: 256
lr: 3e-3

# Config for DuoRec
max_item_seq_len: 20
n_embd: 256
n_layer: 2
n_head: 2
n_inner: 256
activation_function: gelu_new
resid_pdrop: 0.0
embd_pdrop: 0.3
attn_pdrop: 0.5
layer_norm_epsilon: 1e-12
initializer_range: 0.02




patience: 3
eval_interval: 1

contrast: 'us'      
sim: 'dot'           
tau: 0.07             
lmd: 0.2              
lmd_sem: 0.2        
loss_type: 'CE'       
